on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: expense vue app push to ECR.
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      working-directory : ../..
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: 1.0
      run: 
        # Build a docker container and push it to ECR 
       
        docker build -t expense_ui_app  .
        echo "Pushing image to ECR..."
        docker tag expense_ui_app:latest 204215401117.dkr.ecr.ap-south-1.amazonaws.com/expense_ui_app:latest
        docker push 204215401117.dkr.ecr.ap-south-1.amazonaws.com/expense_ui_app:latest